### ISSUE TITLE
Get in touch

### ISSUE THREAD

**Issue by macdonaldr93** [ryanmacdonald/Ray-Tracing-GPU#1]
Hey Ryan!

I know this a bit of a strange way to reach out to you haha but, I didn't really have another way that I could get in touch from GitHub. Would you mind getting in touch with me? My email is `hi@ryanmacdonald.ca`. I'd like to discuss your GitHub username and if you'd be open to changing it. Thanks!

**Comment by ryanmacdonald** [comment]
Hey, sorry, not interested in changing at this time
